basePath: /api
definitions:
  model.ApplyApiKeyRequest:
    properties:
      api_key_name:
        type: string
    type: object
  model.UploadApiKeyRequest:
    properties:
      api_key:
        type: string
      api_key_name:
        type: string
    type: object
  model.UploadStrategyRequest:
    properties:
      address_block_list:
        items:
          type: string
        type: array
      chain_id_whitelist:
        items:
          type: string
        type: array
      day_max_usd:
        type: number
      description:
        type: string
      end_time:
        type: integer
      global_max_usd:
        type: number
      per_user_max_usd:
        type: number
      project_code:
        type: string
      start_time:
        type: integer
      strategy_code:
        type: string
      strategy_name:
        type: string
    type: object
  oauth.PasswordRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    name: AAStar BackEndDashBoard
    url: https://aastar.xyz
  title: AAStar BackEndDashBoard API
  version: v1
paths:
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/api_key:
    delete:
      consumes:
      - application/json
      description: DeleteApiKey
      parameters:
      - description: Api Key
        in: query
        name: api_key
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - DeleteApiKey
    get:
      consumes:
      - application/json
      description: GetApiKey
      parameters:
      - description: Api Key
        in: query
        name: api_key
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetApiKey
    put:
      consumes:
      - application/json
      description: UpdateApiKey
      parameters:
      - description: UploadApiKeyRequest Model
        in: body
        name: uploadApiKeyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadApiKeyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - UpdateApiKey
  /api/v1/api_key/apply:
    post:
      consumes:
      - application/json
      description: ApplyApiKey
      parameters:
      - description: UploadApiKeyRequest Model
        in: body
        name: applyApiKeyRequest
        required: true
        schema:
          $ref: '#/definitions/model.ApplyApiKeyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - ApplyApiKey
  /api/v1/api_key/list:
    get:
      consumes:
      - application/json
      description: GetApiKeyList
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetApiKeyList
  /api/v1/paymaster_strategy:
    delete:
      consumes:
      - application/json
      description: DeleteStrategy
      parameters:
      - description: PaymasterStrategy Code
        in: query
        name: strategy_code
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - DeleteStrategy
    get:
      consumes:
      - application/json
      description: GetStrategy
      parameters:
      - description: PaymasterStrategy Code
        in: query
        name: strategy_code
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetStrategy
    post:
      consumes:
      - application/json
      description: AddStrategy
      parameters:
      - description: UploadStrategyRequest Model
        in: body
        name: uploadStrategyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadStrategyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - AddStrategy
    put:
      consumes:
      - application/json
      description: UpdateStrategy
      parameters:
      - description: UploadStrategyRequest Model
        in: body
        name: uploadStrategyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadStrategyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - UpdateStrategy
  /api/v1/paymaster_strategy/list:
    get:
      consumes:
      - application/json
      description: GetStrategyList
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetStrategyList
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: GetUserInfo
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetUserInfo
  /oauth/github:
    get:
      consumes:
      - application/json
      description: Github OAuth Login
      parameters:
      - description: Github OAuth Code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - OAuth
  /oauth/password:
    post:
      consumes:
      - application/json
      description: PasswordOauthLogin
      parameters:
      - description: PasswordRequest Model
        in: body
        name: passwordRequest
        required: true
        schema:
          $ref: '#/definitions/oauth.PasswordRequest'
      responses:
        "200":
          description: OK
      tags:
      - Oauth
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
