basePath: /api
definitions:
  controller.ChangeStrategyStatusRequest:
    properties:
      status:
        type: string
      strategy_code:
        type: string
    type: object
  controller.DepositSponsorRequest:
    properties:
      is_test_net:
        type: boolean
      tx_hash:
        type: string
    type: object
  controller.WithdrawSponsorRequest:
    type: object
  model.ApplyApiKeyRequest:
    properties:
      api_key_name:
        type: string
      domain_whitelist:
        items:
          type: string
        type: array
      erc20_paymaster_enable:
        type: boolean
      ip_white_list:
        items:
          type: string
        type: array
      network_limit_enable:
        type: boolean
      paymaster_enable:
        type: boolean
      project_sponsor_paymaster_enable:
        type: boolean
      user_pay_paymaster_enable:
        type: boolean
    type: object
  model.UploadApiKeyRequest:
    properties:
      api_key:
        type: string
      api_key_name:
        type: string
      domain_whitelist:
        items:
          type: string
        type: array
      erc20_paymaster_enable:
        type: boolean
      ip_white_list:
        items:
          type: string
        type: array
      network_limit_enable:
        type: boolean
      paymaster_enable:
        type: boolean
      project_sponsor_paymaster_enable:
        type: boolean
      user_pay_paymaster_enable:
        type: boolean
    type: object
  model.UploadStrategyRequest:
    properties:
      address_block_list:
        items:
          type: string
        type: array
      chain_id_whitelist:
        items:
          type: string
        type: array
      day_max_usd:
        type: number
      description:
        type: string
      end_time:
        type: integer
      global_max_usd:
        type: number
      per_user_max_usd:
        type: number
      project_code:
        type: string
      start_time:
        type: integer
      strategy_code:
        type: string
      strategy_name:
        type: string
    type: object
  oauth.PasswordRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    name: AAStar BackEndDashBoard
    url: https://aastar.xyz
  title: AAStar BackEndDashBoard API
  version: v1
paths:
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/api_key:
    delete:
      consumes:
      - application/json
      description: DeleteApiKey
      parameters:
      - description: Api Key
        in: query
        name: api_key
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - DeleteApiKey
    get:
      consumes:
      - application/json
      description: GetApiKey
      parameters:
      - description: Api Key
        in: query
        name: api_key
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetApiKey
    put:
      consumes:
      - application/json
      description: UpdateApiKey
      parameters:
      - description: UploadApiKeyRequest Model
        in: body
        name: uploadApiKeyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadApiKeyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - UpdateApiKey
  /api/v1/api_key/apply:
    post:
      consumes:
      - application/json
      description: ApplyApiKey
      parameters:
      - description: UploadApiKeyRequest Model
        in: body
        name: applyApiKeyRequest
        required: true
        schema:
          $ref: '#/definitions/model.ApplyApiKeyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - ApplyApiKey
  /api/v1/api_key/list:
    get:
      consumes:
      - application/json
      description: GetApiKeyList
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetApiKeyList
  /api/v1/data/api_keys_data_overview:
    get:
      consumes:
      - application/json
      description: DataViewApiKeysOverView
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewApiKeysOverView
      tags:
      - DataViewApiKeysOverView
  /api/v1/data/balance:
    get:
      consumes:
      - application/json
      description: DataViewGetBalance
      parameters:
      - description: is_test_net
        in: query
        name: is_test_net
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewGetBalance
      tags:
      - DataViewGetBalance
  /api/v1/data/paymaster_pay_type_metrics:
    get:
      consumes:
      - application/json
      description: DataViewPaymasterPayTypeMetrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewPaymasterPayTypeMetrics
      tags:
      - DataViewPaymasterPayTypeMetrics
  /api/v1/data/paymaster_requests:
    get:
      consumes:
      - application/json
      description: DataViewApiKeyPaymasterRecallDetailList
      parameters:
      - description: Api Key
        in: query
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewApiKeyPaymasterRecallDetailList
      tags:
      - DataViewApiKeyPaymasterRecallDetailList
  /api/v1/data/request_health_list:
    get:
      consumes:
      - application/json
      description: DataViewRequestHealth
      parameters:
      - description: Api Key
        in: query
        name: api_key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewRequestHealth
      tags:
      - DataViewRequestHealth
  /api/v1/data/request_health_one:
    get:
      consumes:
      - application/json
      description: DataViewRequestHealthOneByApiKey
      parameters:
      - description: API Key
        in: query
        name: api_key
        required: true
        type: string
      - description: Time Type
        in: query
        name: time_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewRequestHealthOneByApiKey
      tags:
      - DataViewRequestHealthOneByApiKey
  /api/v1/data/sponsor_transaction_list:
    get:
      consumes:
      - application/json
      description: DataViewGetSponsorTransactionList
      parameters:
      - description: is_test_net
        in: query
        name: is_test_net
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewGetSponsorTransactionList
      tags:
      - DataViewGetSponsorTransactionList
  /api/v1/data/sponsored_metrics:
    get:
      consumes:
      - application/json
      description: DataViewSponsoredMetrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: DataViewSponsoredMetrics
      tags:
      - DataViewSponsoredMetrics
  /api/v1/paymaster_strategy:
    delete:
      consumes:
      - application/json
      description: DeleteStrategy
      parameters:
      - description: PaymasterStrategy Code
        in: query
        name: strategy_code
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - DeleteStrategy
    get:
      consumes:
      - application/json
      description: GetStrategy
      parameters:
      - description: PaymasterStrategy Code
        in: query
        name: strategy_code
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetStrategy
    post:
      consumes:
      - application/json
      description: AddStrategy
      parameters:
      - description: UploadStrategyRequest Model
        in: body
        name: uploadStrategyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadStrategyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - AddStrategy
    put:
      consumes:
      - application/json
      description: UpdateStrategy
      parameters:
      - description: UploadStrategyRequest Model
        in: body
        name: uploadStrategyRequest
        required: true
        schema:
          $ref: '#/definitions/model.UploadStrategyRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - UpdateStrategy
  /api/v1/paymaster_strategy/list:
    get:
      consumes:
      - application/json
      description: GetStrategyList
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetStrategyList
  /api/v1/paymaster_strategy/switch_status:
    put:
      consumes:
      - application/json
      description: SwitchStrategyStatus
      parameters:
      - description: ChangeStrategyStatusRequest Model
        in: body
        name: ChangeStrategyStatusRequest
        required: true
        schema:
          $ref: '#/definitions/controller.ChangeStrategyStatusRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - SwitchStrategyStatus
  /api/v1/sponsor/deposit:
    post:
      consumes:
      - application/json
      description: SponsorDeposit
      parameters:
      - description: DepositSponsorRequest Model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.DepositSponsorRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: SponsorDeposit
      tags:
      - Sponsor
  /api/v1/sponsor/withdraw:
    post:
      consumes:
      - application/json
      description: SponsorWithdraw
      parameters:
      - description: WithdrawSponsorRequest Model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.WithdrawSponsorRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      summary: SponsorWithdraw
      tags:
      - Sponsor
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: GetUserInfo
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - GetUserInfo
  /oauth/github:
    get:
      consumes:
      - application/json
      description: Github OAuth Login
      parameters:
      - description: Github OAuth Code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - OAuth
  /oauth/password:
    post:
      consumes:
      - application/json
      description: PasswordOauthLogin
      parameters:
      - description: PasswordRequest Model
        in: body
        name: passwordRequest
        required: true
        schema:
          $ref: '#/definitions/oauth.PasswordRequest'
      responses:
        "200":
          description: OK
      tags:
      - Oauth
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
